image:
  repository: jwkohnen/conntrack-stats-exporter
  tag: v0.2.2
  pullPolicy: IfNotPresent

scrape: true
port: 9371

tolerations:
  # catch-all toleration
  - operator: Exists

resources:
  requests:
    cpu: 1m
    memory: 8Mi
  limits:
    cpu: 20m
    memory: 15Mi

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

affinity: {}
