# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/approve-authorization/server/ruby/"
    schedule:
      interval: "weekly"
      day: "thursday"
  - package-ecosystem: "bundler"
    directory: "/create-cardholders-and-cards/server/ruby/"
    schedule:
      interval: "weekly"
      day: "thursday"

  # python dependencies
  - package-ecosystem: "pip"
    directory: "/create-cardholders-and-cards/server/python/"
    schedule:
      interval: "weekly"
      day: "thursday"

  # php dependencies
  - package-ecosystem: "composer"
    directory: "/create-cardholders-and-cards/server/php/"
    schedule:
      interval: "weekly"
      day: "thursday"

  # node dependencies
  - package-ecosystem: "npm"
    directory: "/create-cardholders-and-cards/server/node/"
    schedule:
      interval: "weekly"
      day: "thursday"

  # go dependencies
  - package-ecosystem: "gomod"
    directory: "/create-cardholders-and-cards/server/go/"
    schedule:
      interval: "weekly"
      day: "thursday"

  # java dependencies
  - package-ecosystem: "maven"
    directory: "/create-cardholders-and-cards/server/java/"
    schedule:
      interval: "weekly"
      day: "thursday"

  # dotnet dependencies
  - package-ecosystem: "nuget"
    directory: "/approve-authorization/server/dotnet/"
    schedule:
      interval: "weekly"
      day: "thursday"
  # dotnet dependencies
  - package-ecosystem: "nuget"
    directory: "/create-cardholders-and-cards/server/dotnet/"
    schedule:
      interval: "weekly"
      day: "thursday"
