language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  skip_cleanup: true
  email: skjnldsv@protonmail.com
  on:
    tags: true
    repo: nextcloud/eslint-config-nextcloud
  api_key:
    secure: LN/1VEXWo9wXRSofAYVr81G+l42RatF3iDlEpfYXRfG6csE8S7rTXacLJlNfr+b/UcyjG7uTnz2nzpJuGERpxCmImaiGBKufhtOjSocTBuJ1qVMgIrnGW3iq1bByNcuDPhChnyZP/tZvcTzu+RWN4K+f4Rm7dX6I3DefwFp3ipyoRrvQDAUSv+7VCFK+duZIi/SqQQEXoc8QY8iVUAWSnmTH6W4tKXCvVzX7hBo9qa1dGMTq29uvIRamx0GGfAnS8k+RQyYDG82KHTNWK3Ldi2mzkANwjjghTBOI7lMSqbafKeZ5ieSqJK2MegkSQQH4KvpF8Mw4VgPqAOakmPX5gnKmBB/2qOVjGInXM7CSpe766+nZ6bB2wex3JuBA9CKdavWZYDEWzYAIdJtKsdrwIXKVsNSFdSRx7AO+gHzS5cJu6emjo4jvs7iM5eBibecuqCsCatqyHgxN3r0IDBALZTyzkvvlFMUtE4EPd0ax3S4SHNjd9XhGCZFmGFCIAhZWDqkDIWBcZ1t6j+2vdD6oDwL0sbtHZNC5qyuFCt6UgRt41Cow972m59xY1B/UJFlTHkaFMKVwrs7P3ORc4xhsTkjDrAuLLf29zfLmEsHOdsWHa08I/dXstDbk/P9T0lbMf8oHjcihJWTtb/H6TgyYfu7cRvRLKqCEoUrdaG+FObk=
