language: rust

services:
  - docker

addons:
  apt:
    packages: [valgrind]

jobs:
  include:
  - os: linux
    arch: amd64
    rust: stable
    env: RDKAFKA_RUN_TESTS=1
  - os: linux
    arch: arm64
    rust: stable
  - os: osx
    rust: stable
  - os: windows
    arch: amd64
    rust: stable-msvc
    env: FEATURES=cmake_build,libz-static

script:
  - ./test_ci.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2826b9d85e25802b3907  # gitter
    on_success: change
    on_failure: always
    on_start: never
