language: rust

rust:
  - stable
  - nightly-2019-10-17

sudo: required

services:
  - docker

os:
  - linux
  - osx

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == nightly*  ]]; then ./test_suite.sh; else cargo build --verbose; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2826b9d85e25802b3907  # gitter
    on_success: change
    on_failure: always
    on_start: never
