language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  skip_cleanup: true
  email: skjnldsv@protonmail.com
  on:
    tags: true
    repo: nextcloud/eslint-config-nextcloud
  api_key:
    secure: CUg0lveWUBm1NAlKAMhp7Tm/Mz72LshNe8kAH0EdFJt1BeVPmSOtOMjtgXu75XOPgC/wS1LsssiLugA2QAbKKe9t7DW3uI2RdJ/EIcvBXlTEvClkGcgXxuI3S/8NOTq4S0gUr8UyX2WRkQUk8/3zl2SFqdyYFVR4QJO7IAbjaDMJ8zSdjjr+Z/qeH1+5yfpJ1cdWw9E395Ha7VZ1QgF0P3oXLNU8w17C60ch3rEw/NWNC0mb8agl6mDv8PlQjP9CT9EIhvUJy62PxQcX2pUPL2kHAbf6kVL+eVt4Qk/9eHhL1MQuj5miDNgwEmmbzoNZ9pGOSpe+YxttnNPksp8gnRvJDMhHfiMMkXOB2BkxZvxoQuJfNX32AB36B7vrTDoRprSxGbl2v+9EHF/VMSpHrjNLdqa86YJ8ZzOIxSw92rz30Lay8qf9PgcUgDS/z/e+MLEzIhmroC8Qj7Mwu1GdJFSN+2jPdJpHibrvLe3GuR8dVZ7Fn//3pI9DeLbNV67USR9FtKJ3iaSBvi4T76o+3cDB+izOpGLsRHtpjG4hH9tjzKI7HiptrXW4pLDCt6ni0w+0KTOhAqqk7TzDMtWT43xpesiy/4rTBhXEka0+o0jEwV6861eLKJbIIyJQXd9PhmQV+KPKChTowK86yi2AGKdBHtWlZv4rstTLrnxEHD4=
