name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  github-token:
    default: ${{github.token}}
    required: false