[package]
name = "open-metrics-client"
version = "0.1.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"
description = "Open Metrics client library allowing users to natively instrument applications."
license = "Apache-2.0 OR MIT"

[dependencies]
owning_ref = "0.4"
prost = "0.7"
prost-types = "0.7"
itoa = "0.4"
dtoa = "0.4"

[dev-dependencies]
pyo3 = "0.13"
async-std = { version = "1", features = ["attributes"] }
tide = "0.15"
criterion = "0.3"

[build-dependencies]
prost-build = "0.7"

[[bench]]
name = "family"
harness = false

[[bench]]
name = "text"
path = "benches/encoding/text.rs"
harness = false
