[package]
name = "rust-open-metrics"
version = "0.1.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owning_ref = "*"
prost = "0.6.1"
prost-types = "0.6.1"

[dev-dependencies]
pyo3 = "*"

[build-dependencies]
prost-build = "0.6"
