[package]
name = "open-metrics-client"
version = "0.6.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"
description = "Open Metrics client library allowing users to natively instrument applications."
license = "Apache-2.0 OR MIT"
keywords = ["openmetrics", "prometheus", "metrics", "instrumentation", "monitoring"]

[workspace]
members = ["derive-text-encode"]

[dependencies]
dtoa = "0.4"
itoa = "0.4"
owning_ref = "0.4"
open-metrics-client-derive-text-encode = { version = "0.1", path = "derive-text-encode" }

[dev-dependencies]
async-std = { version = "1", features = ["attributes"] }
criterion = "0.3"
http-types = "2"
pyo3 = "0.13"
tide = "0.16"

[[bench]]
name = "family"
harness = false

[[bench]]
name = "text"
path = "benches/encoding/text.rs"
harness = false
