[package]
name = "redismodule"
version = "0.1.0"
authors = ["Gavrie Philipson <gavrie@redislabs.com>"]
edition = "2018"
build = "build.rs"
description = "A toolkit for building Redis modules in Rust"
license = "MIT"
repository = ""

[[example]]
name = "hello"
crate-type = ["cdylib"]

[[example]]
name = "data_type"
crate-type = ["cdylib"]

[dependencies]
bitflags = "1.0"
libc = "0.2"
time = "0.1"

[build-dependencies]
bindgen = "0.47"
cc = "1.0"
