# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-openetelemetry-lib
  description: Buildkite Pipeline for openetelemetry-lib
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/openetelemetry-lib

spec:
  type: buildkite-pipeline
  owner: group:obs-infraobs-integrations
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: openetelemetry-lib
      description: Golang library containing common code for OpenTelemetry<>Elastic compatibility
    spec:
      repository: elastic/openetelemetry-lib
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        obs-infraobs-integrations:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
