version: '3'
services:
  tempo:
    image: grafana/tempo:latest
    command: ['-config.file=/etc/tempo.yaml']
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    ports:
      - '3200:3200' # tempo
      - '4317:4317' # otlp grpc
