name: CI

on: [pull_request]

jobs:
  test:
    name: Build and run the unit tests using the latest rust.
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name:
          - stable
        os:
          - ubuntu-latest
          - macos-latest
        redis-version:
          - 6-0
          - 6-2
          - 7-0
          - 7-2
        toolchain:
          - 1.78.0
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
            submodules: recursive
      - name: Setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Install toolchain
        id: tc
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Setup cache
        if: runner.os != 'macOS'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-test-${{ steps.tc.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Format and clippy
        run: |
            cargo fmt --all -- --check
            cargo clippy --all-targets --no-default-features --features min-redis-compatibility-version-${{ matrix.redis-version }}

      - name: Install redis
        run: |
            export HOMEBREW_NO_AUTO_UPDATE=1
            ./deps/readies/bin/getredis -v '${{ matrix.redis-version }}' --force ''
            redis-server --version

      - name: Build debug
        run: cargo build --no-default-features --features min-redis-compatibility-version-${{ matrix.redis-version }}

      - name: Build release
        run: cargo build --release --no-default-features --features min-redis-compatibility-version-${{ matrix.redis-version }}

      - name: Test
        run: cargo test --no-default-features --features min-redis-compatibility-version-${{ matrix.redis-version }}

      - name: Doc
        run: cargo doc --all-features
