name: CI

on: [pull_request]

jobs:
  test:
    name: Build and run the unit tests using the latest rust.
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name:
          - stable
        os:
          - ubuntu-latest
          - macos-latest
        redis-version:
          - 6-0
          - 6-2
          - 7-0
          - 7-2
        toolchain:
          - 1.78.0
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        id: tc
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Setup cache
        if: runner.os != 'macOS'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-test-${{ steps.tc.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Format and clippy
        run: |
            cargo fmt --all -- --check
            cargo clippy --all-targets --all-features

      - name: Build, test and doc for the available redis versions
        run: |
            cargo build --no-default-features --features min-redis-compatibility-version-${{ matrix.redis-version }}
            cargo test --no-default-features --features min-redis-compatibility-version-${{ matrix.redis-version }}
            cargo doc --all-features
