name: Sync branches

on:
  workflow_dispatch:
    inputs:
      source:
        description: Source ref (branch or sha)
        required: true
        type: string
      target:
        description: Target branch
        required: true
        type: choice
        options:
          - production


jobs:
  check:
    name: Validate source and target refs
    timeout-minutes: 1
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.source }}
          fetch-depth: 0

      - name: Check ancestry
        if: ${{ github.event.inputs.target == 'production' }}
        run: |
          if ! git merge-base --is-ancestor ${{ github.event.inputs.source }} origin/main; then
            echo "Target is production and source ref isn't an ancestor of main"
            exit 1
          fi


  sync:
    name: Sync source and target refs
    needs: check
    if: ${{ success() }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.FE_RELEASE_TOKEN }}
          ref: ${{ (github.event.inputs.target == 'production' && github.event.inputs.source) || 'main' }}
          fetch-depth: 0

      - name: Release to production
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'production' }}
        run: |
          git push https://${GITHUB_ACTOR}:${{ secrets.FE_RELEASE_TOKEN }}@github.com/${{ github.repository }}.git HEAD:prod-beta
          git push https://${GITHUB_ACTOR}:${{ secrets.FE_RELEASE_TOKEN }}@github.com/${{ github.repository }}.git HEAD:prod-stable
