name: create_release_from_tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make script executeable
        run: chmod + ./scripts/update_documentation.sh
      - name: Checkout Documentation
        uses: actions/checkout@v4
        with:
          repository: 'TophrC-dd/documentation'
          sparse-checkout: 'content/en/serverless/azure_app_services/azure_app_services_linux.md'
          path: 'Dataog-documentation'
      - name: Checkout Documentation
        run: VERSION=${{ github.ref_name }} ./scripts/update_documentation.sh
