name: create_release_from_tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make script executeable
        run: chmod + ./scripts/update_documentation.sh
      - name: Execute update scripts
        run: VERSION=${{ github.ref_name }} ./scripts/update_documentation.sh
